
import java.awt.*;
import java.awt.event.*;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author �?ביעד
 */

public class AddClient extends javax.swing.JFrame {
    
    static int MAX_DIG_PHONE = 7;
    /**
     * Creates new form AddClient
     */
    public AddClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - Aviad Brown
    private void initComponents() {
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        txt_First_Name = new JTextField();
        txt_Last_Name = new JTextField();
        txt_Phone_M = new JTextField();
        txt_Phone_H = new JTextField();
        txt_Address = new JTextField();
        jLabel7 = new JLabel();
        btn_Add = new JButton();
        btn_Cancel = new JButton();
        btn_Clear = new JButton();
        jScrollPane1 = new JScrollPane();
        txt_Comments = new JTextArea();
        cmb_M_Phone = new JComboBox<>();
        cmb_H_Phone = new JComboBox<>();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        var contentPane = getContentPane();

        //======== jPanel1 ========
        {
            jPanel1.setBackground(new Color(204, 204, 255));
            jPanel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder(new javax.swing.
            border.EmptyBorder(0,0,0,0), "JFor\u006dDesi\u0067ner \u0045valu\u0061tion",javax.swing.border.TitledBorder.CENTER
            ,javax.swing.border.TitledBorder.BOTTOM,new java.awt.Font("Dia\u006cog",java.awt.Font
            .BOLD,12),java.awt.Color.red),jPanel1. getBorder()));jPanel1. addPropertyChangeListener(
            new java.beans.PropertyChangeListener(){@Override public void propertyChange(java.beans.PropertyChangeEvent e){if("bord\u0065r"
            .equals(e.getPropertyName()))throw new RuntimeException();}});

            //---- jLabel1 ----
            jLabel1.setFont(new Font("Arial Black", Font.PLAIN, 36));
            jLabel1.setForeground(new Color(51, 0, 204));
            jLabel1.setText("New Client");
            jLabel1.setToolTipText("");

            //---- jLabel2 ----
            jLabel2.setFont(new Font("Arial", Font.BOLD, 14));
            jLabel2.setText("First Name:");

            //---- jLabel3 ----
            jLabel3.setFont(new Font("Arial", Font.BOLD, 14));
            jLabel3.setText("Last Name:");

            //---- jLabel4 ----
            jLabel4.setFont(new Font("Arial", Font.BOLD, 14));
            jLabel4.setText("Address:");

            //---- jLabel5 ----
            jLabel5.setFont(new Font("Arial", Font.BOLD, 14));
            jLabel5.setText("Mobile Phone:");

            //---- jLabel6 ----
            jLabel6.setFont(new Font("Arial", Font.BOLD, 14));
            jLabel6.setText("Phone (Home):");

            //---- txt_First_Name ----
            txt_First_Name.setFont(new Font("Tahoma", Font.PLAIN, 14));
            txt_First_Name.addActionListener(e -> txt_First_NameActionPerformed(e));

            //---- txt_Last_Name ----
            txt_Last_Name.setFont(new Font("Tahoma", Font.PLAIN, 14));

            //---- txt_Phone_M ----
            txt_Phone_M.setFont(new Font("Tahoma", Font.PLAIN, 14));
            txt_Phone_M.addActionListener(e -> txt_Phone_MActionPerformed(e));
            txt_Phone_M.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    txt_Phone_MKeyTyped(e);
                }
            });

            //---- txt_Phone_H ----
            txt_Phone_H.setFont(new Font("Tahoma", Font.PLAIN, 14));
            txt_Phone_H.addActionListener(e -> txt_Phone_HActionPerformed(e));
            txt_Phone_H.addKeyListener(new KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent e) {
                    txt_Phone_HKeyTyped(e);
                }
            });

            //---- txt_Address ----
            txt_Address.setFont(new Font("Tahoma", Font.PLAIN, 14));
            txt_Address.addActionListener(e -> txt_AddressActionPerformed(e));

            //---- jLabel7 ----
            jLabel7.setFont(new Font("Arial", Font.BOLD, 14));
            jLabel7.setText("Comments:");

            //---- btn_Add ----
            btn_Add.setFont(new Font("Arial Black", Font.PLAIN, 14));
            btn_Add.setText("Add");
            btn_Add.addActionListener(e -> btn_AddActionPerformed(e));

            //---- btn_Cancel ----
            btn_Cancel.setFont(new Font("Arial Black", Font.PLAIN, 14));
            btn_Cancel.setText("Cancel");
            btn_Cancel.addActionListener(e -> btn_CancelActionPerformed(e));

            //---- btn_Clear ----
            btn_Clear.setFont(new Font("Arial Black", Font.PLAIN, 14));
            btn_Clear.setText("Clear");
            btn_Clear.addActionListener(e -> btn_ClearActionPerformed(e));

            //======== jScrollPane1 ========
            {

                //---- txt_Comments ----
                txt_Comments.setColumns(20);
                txt_Comments.setLineWrap(true);
                txt_Comments.setRows(5);
                jScrollPane1.setViewportView(txt_Comments);
            }

            //---- cmb_M_Phone ----
            cmb_M_Phone.setModel(new DefaultComboBoxModel<>(new String[] {
                "050",
                "052",
                "053",
                "054",
                "055",
                "058"
            }));
            cmb_M_Phone.addActionListener(e -> cmb_M_PhoneActionPerformed(e));

            //---- cmb_H_Phone ----
            cmb_H_Phone.setModel(new DefaultComboBoxModel<>(new String[] {
                "02",
                "03",
                "04",
                "06",
                "07",
                "08",
                "09",
                "072",
                " ",
                " "
            }));
            cmb_H_Phone.addActionListener(e -> cmb_H_PhoneActionPerformed(e));

            GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 232, GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Address))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Cancel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Clear, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Add, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_First_Name))
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Last_Name))
                                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup()
                                            .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup()
                                            .addComponent(jScrollPane1)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup()
                                                    .addComponent(cmb_M_Phone, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cmb_H_Phone, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup()
                                                    .addComponent(txt_Phone_H, GroupLayout.Alignment.TRAILING)
                                                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(txt_Phone_M, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                                .addGap(48, 48, 48))))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup()
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_First_Name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Last_Name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txt_Phone_M, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmb_M_Phone))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup()
                                .addComponent(jLabel6)
                                .addComponent(txt_Phone_H, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmb_H_Phone, GroupLayout.Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addComponent(jLabel4)
                            .addComponent(txt_Address, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup()
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Add, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Cancel, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Clear, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
            );
        }

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 405, GroupLayout.PREFERRED_SIZE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Phone_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Phone_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Phone_MActionPerformed

    private void txt_Phone_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Phone_HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Phone_HActionPerformed

    private void txt_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AddressActionPerformed

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
        if ((txt_First_Name.getText().equals("")) && (txt_Last_Name.getText().equals(""))) //if no name was given
        {
            handleError.showErrorMessage(true, "Please give a name for the client", "No Name");
            return;
        }
        String fname = txt_First_Name.getText();
        String lname = txt_Last_Name.getText();
        String mphone = txt_Phone_M.getText();
        if (mphone.length()<MAX_DIG_PHONE) //phone number is too short
        {
            handleError.showErrorMessage(true, "The phone number is not valid", "Phone Not Valid");
            return;
        }
        if (mphone.length()>0) //if  no mobile phone, mphone stay empty
            mphone = cmb_M_Phone.getSelectedItem() + mphone;

        //debug
        System.out.println(mphone);
        
        String hphone = txt_Phone_H.getText(); 
        if (hphone.length()>0) //if  no mobile phone, mphone stay empty
            hphone = cmb_H_Phone.getSelectedItem() + hphone;
        
        //debug
        System.out.println(hphone);
        String address = txt_Address.getText();
        String comments = txt_Comments.getText();
        //debug
        System.out.println(fname);
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Calendar cal = Calendar.getInstance();
        String date = dateFormat.format(cal.getTime());
        System.out.println(date);
        client c = new client();
        c.insertUpdateDeleteClient('i', null, fname, lname, address, mphone, hphone, comments, date);
    }//GEN-LAST:event_btn_AddActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        txt_First_Name.setText("");
        txt_Last_Name.setText("");
        txt_Address.setText("");
        txt_Comments.setText("");
        txt_Phone_M.setText("");
        txt_Phone_H.setText("");
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void txt_First_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_First_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_First_NameActionPerformed

    private void txt_Phone_MKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Phone_MKeyTyped
        if (!(Character.isDigit(evt.getKeyChar())))
            evt.consume(); 
        if(txt_Phone_M.getText().length()>=MAX_DIG_PHONE)  
            evt.consume();
    }//GEN-LAST:event_txt_Phone_MKeyTyped

    private void txt_Phone_HKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Phone_HKeyTyped
        if (!(Character.isDigit(evt.getKeyChar())))
            evt.consume();
        if(txt_Phone_H.getText().length()>=MAX_DIG_PHONE)  
            evt.consume();        
    }//GEN-LAST:event_txt_Phone_HKeyTyped

    private void cmb_M_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_M_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_M_PhoneActionPerformed

    private void cmb_H_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_H_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_H_PhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - Aviad Brown
    private JPanel jPanel1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JTextField txt_First_Name;
    private JTextField txt_Last_Name;
    private JTextField txt_Phone_M;
    private JTextField txt_Phone_H;
    private JTextField txt_Address;
    private JLabel jLabel7;
    private JButton btn_Add;
    private JButton btn_Cancel;
    private JButton btn_Clear;
    private JScrollPane jScrollPane1;
    private JTextArea txt_Comments;
    private JComboBox<String> cmb_M_Phone;
    private JComboBox<String> cmb_H_Phone;
    // End of variables declaration//GEN-END:variables
}
