
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author �?ביעד
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {                
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_U.setVisible(false);
        lbl_P.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - Aviad Brown
	private void initComponents() {
		jLabel1 = new JLabel();
		label_U = new JLabel();
		label_P = new JLabel();
		jTextField_Username = new JTextField();
		jPasswordField = new JPasswordField();
		jButton_Login = new JButton();
		jButton_Cancel = new JButton();
		lbl_U = new JLabel();
		lbl_P = new JLabel();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		Container contentPane = getContentPane();

		//---- jLabel1 ----
		jLabel1.setFont(new Font("Arial", Font.BOLD, 24));
		jLabel1.setText("Login");

		//---- label_U ----
		label_U.setFont(new Font("Tahoma", Font.BOLD, 14));
		label_U.setText("Username:");

		//---- label_P ----
		label_P.setFont(new Font("Tahoma", Font.BOLD, 14));
		label_P.setText("Password:");

		//---- jTextField_Username ----
		jTextField_Username.setFont(new Font("Tahoma", Font.PLAIN, 14));
		jTextField_Username.addActionListener(e -> jTextField_UsernameActionPerformed(e));

		//---- jPasswordField ----
		jPasswordField.setFont(new Font("Tahoma", Font.PLAIN, 14));

		//---- jButton_Login ----
		jButton_Login.setFont(new Font("Tahoma", Font.BOLD, 12));
		jButton_Login.setText("Login");
		jButton_Login.addActionListener(e -> jButton_LoginActionPerformed(e));

		//---- jButton_Cancel ----
		jButton_Cancel.setFont(new Font("Tahoma", Font.BOLD, 12));
		jButton_Cancel.setText("Cancel");
		jButton_Cancel.addActionListener(e -> jButton_CancelActionPerformed(e));

		//---- lbl_U ----
		lbl_U.setFont(new Font("Tahoma", Font.BOLD, 14));
		lbl_U.setForeground(new Color(255, 0, 51));
		lbl_U.setText("*");

		//---- lbl_P ----
		lbl_P.setFont(new Font("Tahoma", Font.BOLD, 14));
		lbl_P.setForeground(new Color(255, 0, 51));
		lbl_P.setText("*");

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
						.addGroup(contentPaneLayout.createSequentialGroup()
							.addContainerGap()
							.addComponent(jButton_Cancel, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
							.addGap(18, 18, 18)
							.addComponent(jButton_Login, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
						.addGroup(GroupLayout.Alignment.LEADING, contentPaneLayout.createSequentialGroup()
							.addGap(24, 24, 24)
							.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
								.addComponent(label_U)
								.addComponent(label_P))
							.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
							.addGroup(contentPaneLayout.createParallelGroup()
								.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
								.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
									.addComponent(jTextField_Username)
									.addComponent(jPasswordField, GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)))))
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addGroup(contentPaneLayout.createParallelGroup()
						.addComponent(lbl_U, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
						.addComponent(lbl_P, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)))
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabel1)
					.addGap(17, 17, 17)
					.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
						.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
							.addComponent(label_P)
							.addComponent(jPasswordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addComponent(lbl_P, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
						.addGroup(contentPaneLayout.createSequentialGroup()
							.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
								.addComponent(label_U)
								.addComponent(jTextField_Username, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(lbl_U, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE))
							.addGap(38, 38, 38)))
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
					.addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
						.addComponent(jButton_Cancel, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton_Login, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE))
					.addGap(21, 21, 21))
		);
		pack();
		setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_UsernameActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        lbl_U.setVisible(false);
        lbl_P.setVisible(false);
        int notValid;
        notValid = 0;
        if (jTextField_Username.getText().equals(""))
        {
            lbl_U.setVisible(true);
            notValid=1;
        }
        if (String.valueOf(jPasswordField.getPassword()).equals("")) 
        {
            lbl_P.setVisible(true);
            notValid=1;
        }
        if (notValid==1) return;
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        try {
            ps = con.prepareStatement("SELECT * FROM user WHERE username = ? AND password= ?");
            ps.setString(1, jTextField_Username.getText());
            ps.setString(2, String.valueOf(jPasswordField.getPassword()));
            
            ResultSet rs = ps.executeQuery();
        
            if (rs.next())
            {
                MainForm mf = new MainForm();
                mf.setVisible(true);
                mf.pack();
                mf.setLocationRelativeTo(null);
                //mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                MainForm.lbl_welcome.setText("Welcome "+ jTextField_Username.getText());
                MainForm.lbl_Clients_c.setText("Clients count: "+ Integer.toString(MyFunction.countData("client")));
                MainForm.lbl_Suppliers_c.setText("Suppliers count: "+ Integer.toString(MyFunction.countData("supplier")));
                MainForm.lbl_Products_c.setText("Products count: "+ Integer.toString(MyFunction.countData("product")));
                MainForm.lbl_Orders_c.setText("Orders count: "+ Integer.toString(MyFunction.countData("order")));                
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Wrong username or password", "Wrong", JOptionPane.INFORMATION_MESSAGE);
                jTextField_Username.setText("");
                jPasswordField.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jButton_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_CancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - Aviad Brown
	private JLabel jLabel1;
	private JLabel label_U;
	private JLabel label_P;
	private JTextField jTextField_Username;
	private JPasswordField jPasswordField;
	private JButton jButton_Login;
	private JButton jButton_Cancel;
	private JLabel lbl_U;
	private JLabel lbl_P;
    // End of variables declaration//GEN-END:variables

    private void integertostring() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
