

import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aviad
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel_title = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_Title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Clients_c = new javax.swing.JLabel();
        lbl_Suppliers_c = new javax.swing.JLabel();
        lbl_Products_c = new javax.swing.JLabel();
        lbl_Orders_c = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_File_Save_As = new javax.swing.JMenuItem();
        jMenuItem_File_Save = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_Manage_Clients = new javax.swing.JMenuItem();
        jMenuItem_Manage_Suppliers = new javax.swing.JMenuItem();
        jMenuItem_Manage_Products = new javax.swing.JMenuItem();
        jMenu_add = new javax.swing.JMenu();
        jMenuItem_Add_Client = new javax.swing.JMenuItem();
        jMenuItem_Add_Supplier = new javax.swing.JMenuItem();
        jMenuItem_Add_Product = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_welcome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(0, 0, 255));
        lbl_welcome.setText("Welcome <#####>");

        lbl_Title.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_Title.setText("Order Management");

        javax.swing.GroupLayout jPanel_titleLayout = new javax.swing.GroupLayout(jPanel_title);
        jPanel_title.setLayout(jPanel_titleLayout);
        jPanel_titleLayout.setHorizontalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addComponent(lbl_welcome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Title)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel_titleLayout.setVerticalGroup(
            jPanel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_titleLayout.createSequentialGroup()
                .addComponent(lbl_welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Statistics:");

        lbl_Clients_c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Clients_c.setText("Clients count:");

        lbl_Suppliers_c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Suppliers_c.setText("Suppliers count:");

        lbl_Products_c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Products_c.setText("Products count:");

        lbl_Orders_c.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Orders_c.setText("orders count:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Suppliers_c, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(lbl_Products_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Orders_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Clients_c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Clients_c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Suppliers_c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Products_c)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Orders_c)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem_File_Save_As.setText("Save As");
        jMenu1.add(jMenuItem_File_Save_As);

        jMenuItem_File_Save.setText("Save");
        jMenuItem_File_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_File_SaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_File_Save);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manage");

        jMenuItem_Manage_Clients.setText("Clients");
        jMenuItem_Manage_Clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Manage_ClientsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Manage_Clients);

        jMenuItem_Manage_Suppliers.setText("Suppliers");
        jMenuItem_Manage_Suppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Manage_SuppliersActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Manage_Suppliers);

        jMenuItem_Manage_Products.setText("Products");
        jMenuItem_Manage_Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Manage_ProductsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_Manage_Products);

        jMenuBar1.add(jMenu2);

        jMenu_add.setText("Add");

        jMenuItem_Add_Client.setText("Client");
        jMenuItem_Add_Client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Add_ClientActionPerformed(evt);
            }
        });
        jMenu_add.add(jMenuItem_Add_Client);

        jMenuItem_Add_Supplier.setText("Supplier");
        jMenuItem_Add_Supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Add_SupplierActionPerformed(evt);
            }
        });
        jMenu_add.add(jMenuItem_Add_Supplier);

        jMenuItem_Add_Product.setText("Product");
        jMenuItem_Add_Product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Add_ProductActionPerformed(evt);
            }
        });
        jMenu_add.add(jMenuItem_Add_Product);

        jMenuBar1.add(jMenu_add);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_File_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_File_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_File_SaveActionPerformed

    private void jMenuItem_Add_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Add_ClientActionPerformed
        AddClient ac = new AddClient();
        ac.setVisible(true);
        ac.pack();
        ac.setLocationRelativeTo(this);
        ac.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_Add_ClientActionPerformed

    private void jMenuItem_Manage_ClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Manage_ClientsActionPerformed
        manageClientsForm mec = new manageClientsForm();
        mec.setVisible(true);
        mec.pack();
        mec.setLocationRelativeTo(this);
        mec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_Manage_ClientsActionPerformed

    private void jMenuItem_Add_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Add_SupplierActionPerformed
        addSupplierForm as = new addSupplierForm();
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(this);
        as.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_Add_SupplierActionPerformed

    private void jMenuItem_Manage_SuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Manage_SuppliersActionPerformed
        manageSupplierForm ms = new manageSupplierForm();
        ms.setVisible(true);
        ms.pack();
        ms.setLocationRelativeTo(this);
        ms.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_Manage_SuppliersActionPerformed

    private void jMenuItem_Add_ProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Add_ProductActionPerformed
        AddProductForm ap = new AddProductForm();
        ap.setVisible(true);
        ap.pack();
        ap.setLocationRelativeTo(this);
        ap.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_Add_ProductActionPerformed

    private void jMenuItem_Manage_ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Manage_ProductsActionPerformed
        manageProductsForm mp = new manageProductsForm();
        mp.setVisible(true);
        mp.pack();
        mp.setLocationRelativeTo(this);
        mp.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem_Manage_ProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_Add_Client;
    private javax.swing.JMenuItem jMenuItem_Add_Product;
    private javax.swing.JMenuItem jMenuItem_Add_Supplier;
    private javax.swing.JMenuItem jMenuItem_File_Save;
    private javax.swing.JMenuItem jMenuItem_File_Save_As;
    private javax.swing.JMenuItem jMenuItem_Manage_Clients;
    private javax.swing.JMenuItem jMenuItem_Manage_Products;
    private javax.swing.JMenuItem jMenuItem_Manage_Suppliers;
    private javax.swing.JMenu jMenu_add;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_title;
    public static javax.swing.JLabel lbl_Clients_c;
    public static javax.swing.JLabel lbl_Orders_c;
    public static javax.swing.JLabel lbl_Products_c;
    public static javax.swing.JLabel lbl_Suppliers_c;
    private javax.swing.JLabel lbl_Title;
    public static javax.swing.JLabel lbl_welcome;
    // End of variables declaration//GEN-END:variables
}
