import java.awt.*;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author �?ביעד
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	// Generated using JFormDesigner Evaluation license - Aviad Brown
	private void initComponents() {
		jMenuBar1 = new JMenuBar();
		jMenu1 = new JMenu();
		jMenuItem_File_Save_As = new JMenuItem();
		jMenuItem_File_Save = new JMenuItem();
		jMenu2 = new JMenu();
		jMenu_add = new JMenu();
		jMenuItem_Add_Client = new JMenuItem();
		jMenuItem_Add_Supplier = new JMenuItem();
		jMenuItem_Add_Product = new JMenuItem();
		jPanel1 = new JPanel();
		jLabel1 = new JLabel();
		lbl_welcome = new JLabel();
		jPanel2 = new JPanel();
		jLabel2 = new JLabel();
		lbl_Clients_c = new JLabel();
		lbl_Suppliers_c = new JLabel();
		lbl_Products_c = new JLabel();
		lbl_Orders_c = new JLabel();
		jMenuItem1 = new JMenuItem();

		//======== this ========
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		Container contentPane = getContentPane();

		//======== jMenuBar1 ========
		{

			//======== jMenu1 ========
			{
				jMenu1.setText("File");

				//---- jMenuItem_File_Save_As ----
				jMenuItem_File_Save_As.setText("Save As");
				jMenu1.add(jMenuItem_File_Save_As);

				//---- jMenuItem_File_Save ----
				jMenuItem_File_Save.setText("Save");
				jMenuItem_File_Save.addActionListener(e -> jMenuItem_File_SaveActionPerformed(e));
				jMenu1.add(jMenuItem_File_Save);
			}
			jMenuBar1.add(jMenu1);

			//======== jMenu2 ========
			{
				jMenu2.setText("Edit");
			}
			jMenuBar1.add(jMenu2);

			//======== jMenu_add ========
			{
				jMenu_add.setText("Add");

				//---- jMenuItem_Add_Client ----
				jMenuItem_Add_Client.setText("Client");
				jMenuItem_Add_Client.addActionListener(e -> jMenuItem_Add_ClientActionPerformed(e));
				jMenu_add.add(jMenuItem_Add_Client);

				//---- jMenuItem_Add_Supplier ----
				jMenuItem_Add_Supplier.setText("Supplier");
				jMenu_add.add(jMenuItem_Add_Supplier);

				//---- jMenuItem_Add_Product ----
				jMenuItem_Add_Product.setText("Product");
				jMenu_add.add(jMenuItem_Add_Product);
			}
			jMenuBar1.add(jMenu_add);
		}
		setJMenuBar(jMenuBar1);

		//======== jPanel1 ========
		{
			jPanel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.TitledBorder(new javax.swing.border
			.EmptyBorder(0,0,0,0), "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn",javax.swing.border.TitledBorder.CENTER,javax
			.swing.border.TitledBorder.BOTTOM,new java.awt.Font("Dia\u006cog",java.awt.Font.BOLD,
			12),java.awt.Color.red),jPanel1. getBorder()));jPanel1. addPropertyChangeListener(new java.beans
			.PropertyChangeListener(){@Override public void propertyChange(java.beans.PropertyChangeEvent e){if("\u0062ord\u0065r".equals(e.
			getPropertyName()))throw new RuntimeException();}});

			//---- jLabel1 ----
			jLabel1.setFont(new Font("Arial", Font.BOLD, 36));
			jLabel1.setText("Order Management");

			//---- lbl_welcome ----
			lbl_welcome.setFont(new Font("Tahoma", Font.BOLD, 14));
			lbl_welcome.setForeground(Color.blue);
			lbl_welcome.setText("Welcome <#####>");

			GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
			jPanel1.setLayout(jPanel1Layout);
			jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup()
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addGap(101, 101, 101)
						.addComponent(jLabel1)
						.addContainerGap(265, Short.MAX_VALUE))
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(lbl_welcome)
						.addGap(0, 0, Short.MAX_VALUE))
			);
			jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup()
					.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(lbl_welcome)
						.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jLabel1)
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
			);
		}

		//======== jPanel2 ========
		{
			jPanel2.setBackground(new Color(204, 204, 255));

			//---- jLabel2 ----
			jLabel2.setFont(new Font("Tahoma", Font.BOLD, 36));
			jLabel2.setText("Statistics:");

			//---- lbl_Clients_c ----
			lbl_Clients_c.setFont(new Font("Tahoma", Font.BOLD, 12));
			lbl_Clients_c.setText("Clients count:");

			//---- lbl_Suppliers_c ----
			lbl_Suppliers_c.setFont(new Font("Tahoma", Font.BOLD, 12));
			lbl_Suppliers_c.setText("Suppliers count:");

			//---- lbl_Products_c ----
			lbl_Products_c.setFont(new Font("Tahoma", Font.BOLD, 12));
			lbl_Products_c.setText("Products count:");

			//---- lbl_Orders_c ----
			lbl_Orders_c.setFont(new Font("Tahoma", Font.BOLD, 12));
			lbl_Orders_c.setText("orders count:");

			GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
			jPanel2.setLayout(jPanel2Layout);
			jPanel2Layout.setHorizontalGroup(
				jPanel2Layout.createParallelGroup()
					.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
					.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
							.addComponent(lbl_Suppliers_c, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
							.addComponent(lbl_Products_c, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(lbl_Orders_c, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(lbl_Clients_c, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 0, Short.MAX_VALUE))
			);
			jPanel2Layout.setVerticalGroup(
				jPanel2Layout.createParallelGroup()
					.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lbl_Clients_c)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lbl_Suppliers_c)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lbl_Products_c)
						.addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(lbl_Orders_c)
						.addGap(0, 31, Short.MAX_VALUE))
			);
		}

		GroupLayout contentPaneLayout = new GroupLayout(contentPane);
		contentPane.setLayout(contentPaneLayout);
		contentPaneLayout.setHorizontalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(0, 504, Short.MAX_VALUE))
				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		contentPaneLayout.setVerticalGroup(
			contentPaneLayout.createParallelGroup()
				.addGroup(contentPaneLayout.createSequentialGroup()
					.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addContainerGap(170, Short.MAX_VALUE))
		);
		pack();
		setLocationRelativeTo(getOwner());

		//---- jMenuItem1 ----
		jMenuItem1.setText("jMenuItem1");
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_File_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_File_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem_File_SaveActionPerformed

    private void jMenuItem_Add_ClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Add_ClientActionPerformed
        AddClient ac = new AddClient();
        ac.setVisible(true);
        ac.pack();
        ac.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_jMenuItem_Add_ClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
	// Generated using JFormDesigner Evaluation license - Aviad Brown
	private JMenuBar jMenuBar1;
	private JMenu jMenu1;
	private JMenuItem jMenuItem_File_Save_As;
	private JMenuItem jMenuItem_File_Save;
	private JMenu jMenu2;
	private JMenu jMenu_add;
	private JMenuItem jMenuItem_Add_Client;
	private JMenuItem jMenuItem_Add_Supplier;
	private JMenuItem jMenuItem_Add_Product;
	private JPanel jPanel1;
	private JLabel jLabel1;
	public static JLabel lbl_welcome;
	private JPanel jPanel2;
	private JLabel jLabel2;
	public static JLabel lbl_Clients_c;
	public static JLabel lbl_Suppliers_c;
	public static JLabel lbl_Products_c;
	public static JLabel lbl_Orders_c;
	private JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
